name: next-cloud
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codes
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm ci
      - name: Build
        run: npm run build:opennextjs
      - name: Deploy
        run: npm run deploy
      - name: Successful
        run: echo "Successfully deployed"
