name: next-cloud
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codes
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm ci
      - name: Install Playwright Browser
        run: npx playwright install --with-deps
      - name: Tests:E2E
        run: npm run test:e2e
      - name: Build
        run: npm run build:opennextjs
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}

      - name: Successful
        run: echo "Successfully deployed"
